import os
import glob
import time
import random
import yaml
import torch
import psutil
from ultralytics import YOLO

try:
    import GPUtil
except ImportError:
    GPUtil = None


# ==============================================================================
# 1. DETERMINISTIC SETUP & REPRODUCIBILITY
# ==============================================================================
def enforce_reproducibility(seed=42):
    """
    Locks random seeds across Python, NumPy, and PyTorch to guarantee
    reproducible model fine-tuning results across multiple experimental runs.
    """
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False


enforce_reproducibility(seed=42)

# Compute backend detection
DEVICE = 0 if torch.cuda.is_available() else "cpu"
GPU_NAME = torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU"


# ==============================================================================
# 2. CACHE PURGING AND DATASET CONFIGURATION
# ==============================================================================
def purge_stale_caches(dataset_dir):
    """
    Recursively scans and removes stale .cache files generated by Ultralytics
    to prevent index mismatches and ensure clean dataset initialization.
    """
    if not os.path.exists(dataset_dir):
        return

    cache_files = glob.glob(os.path.join(dataset_dir, "**", "*.cache"), recursive=True)
    for cf in cache_files:
        try:
            os.remove(cf)
            print(f"[CACHE PURGE] Cleared stale tracking artifact: {cf}")
        except Exception as e:
            print(f"[WARN] Failed to delete cache file {cf}: {e}")


def generate_visdrone_yaml(train_dir, val_dir, output_path="visdrone_finetune.yaml"):
    """
    Dynamically generates the dataset YAML configuration for the 10-class VisDrone setup.
    """
    train_abs = os.path.abspath(train_dir)
    val_abs = os.path.abspath(val_dir)

    yaml_content = {
        "path": os.path.abspath("."),
        "train": train_abs,
        "val": val_abs,
        "nc": 10,
        "names": {
            0: "pedestrian",
            1: "person",
            2: "car",
            3: "van",
            4: "bus",
            5: "truck",
            6: "motor",
            7: "bicycle",
            8: "awning-tricycle",
            9: "tricycle"
        }
    }

    with open(output_path, "w", encoding="utf-8") as f:
        yaml.dump(yaml_content, f, default_flow_style=False, sort_keys=False)

    print(f"[CONFIG] Dataset YAML configuration generated at: {os.path.abspath(output_path)}")
    return output_path


# ==============================================================================
# 3. FINE-TUNING EXECUTION PIPELINE
# ==============================================================================
def run_finetune_pipeline(
        weights_path="yolov8n.pt",
        train_img_dir=r"./data/VisDrone2019-DET-train/images",
        val_img_dir=r"./data/VisDrone2019-DET-val/images",
        epochs=100,
        imgsz=640,
        batch_size=16,
        lr0=0.005,
        optimizer="AdamW",
        project="runs/finetune_visdrone",
        experiment_name="yolov8n_visdrone_ft"
):
    """
    Executes fine-tuning for lightweight YOLO object detectors on VisDrone.
    """
    print("\n" + "=" * 80)
    print(f"[*] Starting Fine-Tuning Task: {experiment_name}")
    print(f"[*] Pretrained Model: {weights_path} | Device Architecture: {GPU_NAME}")
    print("=" * 80)

    # Step 1: Purge existing label caches
    purge_stale_caches(os.path.dirname(train_img_dir))
    purge_stale_caches(os.path.dirname(val_img_dir))

    # Step 2: Build dataset profile
    data_yaml = generate_visdrone_yaml(train_img_dir, val_img_dir)

    # Step 3: Load pretrained checkpoint
    model = YOLO(weights_path)

    # Step 4: Run training loop with aerial-optimized hyperparameters
    results = model.train(
        data=data_yaml,
        epochs=epochs,
        imgsz=imgsz,
        batch=batch_size,
        device=DEVICE,

        # Optimization settings (Lower initial learning rate to preserve pretrained features)
        optimizer=optimizer,
        lr0=lr0,
        lrf=0.01,
        warmup_epochs=3.0,
        weight_decay=0.0005,

        # Data augmentation settings tailored for small/dense UAV targets
        mosaic=1.0,
        mixup=0.15,
        degrees=10.0,
        scale=0.5,

        # Output directory and reproducibility tracking
        project=project,
        name=experiment_name,
        exist_ok=True,
        pretrained=True,
        seed=42,
        deterministic=True,
        save=True,
        val=True,
        plots=True,
        verbose=True
    )

    print("\n" + "=" * 80)
    print(f"[+] Fine-Tuning Task Completed Successfully!")
    print(f"    ├─ Best Model Saved At: {os.path.join(project, experiment_name, 'weights', 'best.pt')}")
    print(f"    └─ Logs & Metrics Saved At: {os.path.join(project, experiment_name)}")
    print("=" * 80)

    return results


if __name__ == "__main__":
    TRAIN_IMAGES = r"./data/VisDrone2019-DET-train/images"
    VAL_IMAGES = r"./data/VisDrone2019-DET-val/images"

    run_finetune_pipeline(
        weights_path="yolov8n.pt",
        train_img_dir=TRAIN_IMAGES,
        val_img_dir=VAL_IMAGES,
        epochs=100,
        imgsz=640,
        batch_size=16,
        lr0=0.005,
        experiment_name="yolov8n_visdrone_ft_e100"
    )